### ISSUE TITLE
Error "Body cannot be blank" when trying to use action when following example from README

### ISSUE THREAD

**Issue by mattwelke** [PoorlyDefinedBehaviour/nyc-reporter#3]
I maintain an open source library. Its existing "test" script created by its original author is `mocha -u tdd -t 30000 -R spec`. I took the example from the README and followed it. My steps ended up looking like:

```yaml
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      # Not using "npm ci" because not using lockfile
      - run: npm i
      - name: Report test coverage
        uses: PoorlyDefinedBehaviour/nyc-reporter@v1
        with:
          command: "npm test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I have my own script I just added for generating a coverage report. So in the end, my scripts look like:

```
"scripts": {
  "coverage": "nyc --reporter json-summary --reporter text mocha -u tdd -t 30000 -R spec",
  "test": "mocha -u tdd -t 30000 -R spec",
  "lint": "semistandard"
}
```

When I run my workflow, I get the following error:

```
Error: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body cannot be blank"}
```

It sounds to me like it's trying to send a PR comment to the GitHub API where the contents of the comment are empty. And the API probably doesn't like this. When I dug into the source code of this action, I got a sense for how it worked. It appears to capture the standard output from executing the report command. And the command `npm test` should be compatible. It seems standard to me. But I notice that if I manually perform the string interpolation that the action source code appears to be doing:

```js
`./node_modules/.bin/nyc --reporter=lcov --reporter=text ${command}`
```

Then I get the final command:

```
./node_modules/.bin/nyc --reporter=lcov --reporter=text mocha -u tdd -t 30000 -R spec
```

And when I run that command on my computer, it doesn't work. I get the following error output:

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn mocha ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn mocha',
  path: 'mocha',
  spawnargs: [ '-u', 'tdd', '-t', '30000', '-R', 'spec' ]
}
```

I also get the error if I run it with a simplified version of the mocha command where it's just `mocha`:

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn mocha ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn mocha',
  path: 'mocha',
  spawnargs: []
}
```

This may explain why the action, when running this command, is unable to get any output to use in its GitHub API call.

However, I don't understand this error, so I don't know what to do at this point. Figured I'd report this though.
